# Generated by Django 5.0.6 on 2024-09-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0035_delete_resume"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название резюме"),
                ),
                ("about", models.TextField(verbose_name="О себе")),
                (
                    "education",
                    models.CharField(
                        choices=[
                            ("none", "Без образования"),
                            ("high_school", "Среднее образование"),
                            ("bachelor", "Бакалавр"),
                            ("master", "Магистр"),
                            ("phd", "Доктор наук"),
                        ],
                        default="none",
                        max_length=20,
                        verbose_name="Уровень образования",
                    ),
                ),
                (
                    "experience",
                    models.CharField(
                        choices=[
                            ("no_experience", "Нет опыта"),
                            ("less_than_1", "Меньше года"),
                            ("1_to_3", "1-3 года"),
                            ("3_to_5", "3-5 лет"),
                            ("more_than_5", "Более 5 лет"),
                        ],
                        default="no_experience",
                        max_length=20,
                        verbose_name="Опыт работы",
                    ),
                ),
                ("skills", models.TextField(verbose_name="Навыки")),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=25,
                        null=True,
                        verbose_name="Телефон для связи",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email для связи",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "active",
                    models.BooleanField(default=True, verbose_name="Резюме активно"),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="users.userprofile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Резюме",
                "verbose_name_plural": "Резюме",
                "ordering": ["-created_at"],
            },
        ),
    ]
