# Generated by Django 5.0.6 on 2024-09-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("resume", "0002_resume_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="resume",
            name="vuz",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Учреждение"
            ),
        ),
    ]
