# Generated by Django 5.0.6 on 2024-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
