# Generated by Django 5.0.6 on 2024-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rooms", "0002_alter_room_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[
                    ("scheduled", "Запланировано"),
                    ("active", "Активно"),
                    ("completed", "Завершено"),
                ],
                default="scheduled",
                max_length=10,
            ),
        ),
    ]
