# Generated by Django 5.0.6 on 2024-06-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='entity_type',
            field=models.CharField(choices=[('individual', 'Физическое лицо'), ('business', 'Юридическое лицо')], default='individual', max_length=10),
        ),
    ]
