# Generated by Django 5.0.6 on 2024-06-25 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, choices=[('tse', 'Астана'), ('ala', 'Алматы'), ('sco', 'Актау'), ('krg', 'Караганда'), ('ust', 'Усть-Каменагорск'), ('shym', 'Шымкент')], max_length=25),
        ),
    ]
