# Generated by Django 5.0.6 on 2024-06-28 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_is_verified_businessverification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualverification',
            name='user',
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_document', models.ImageField(blank=True, null=True, upload_to='id_documents/')),
                ('business_license', models.ImageField(blank=True, null=True, upload_to='business_licenses/')),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='BusinessVerification',
        ),
        migrations.DeleteModel(
            name='IndividualVerification',
        ),
    ]
