# Generated by Django 5.0.6 on 2024-06-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_verificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
