# Generated by Django 5.0.6 on 2024-06-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_delete_verificationrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='verification',
            options={'verbose_name': 'Верификация', 'verbose_name_plural': 'Верификации'},
        ),
        migrations.AddField(
            model_name='verification',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=20, verbose_name='Статус верификации'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='business_licenses/', verbose_name='Лицензия на деятельность'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id_document',
            field=models.ImageField(blank=True, null=True, upload_to='id_documents/', verbose_name='Документ удостоверяющий личность'),
        ),
        migrations.AlterField(
            model_name='verification',
            name='tax_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Налоговый идентификационный номер'),
        ),
    ]
