# Generated by Django 5.0.6 on 2024-07-09 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_userprofile_language_alter_user_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='entity_type',
        ),
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('verified', models.BooleanField(default=False)),
                ('documents', models.FileField(upload_to='company_docs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профили компаний',
            },
        ),
    ]
