# Generated by Django 5.0.6 on 2024-08-22 08:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0020_alter_user_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "company_name",
                    models.CharField(max_length=200, verbose_name="Название компании"),
                ),
                (
                    "document",
                    models.FileField(upload_to="documents/", verbose_name="Документ"),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=20, verbose_name="Номер телефона"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True, null=True, verbose_name="Сайт (если есть)"
                    ),
                ),
            ],
        ),
    ]
