# Generated by Django 5.0.6 on 2024-08-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_employerrequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerrequest",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="documents/", verbose_name="Документ"
            ),
        ),
        migrations.AlterField(
            model_name="employerrequest",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Сайт"),
        ),
    ]
