# Generated by Django 5.0.6 on 2024-08-23 17:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_alter_employerrequest_document_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="name",
        ),
    ]
