# Generated by Django 5.0.6 on 2024-08-24 11:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_delete_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="last_post_date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="posts_today",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
