# Generated by Django 5.0.6 on 2024-08-24 13:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_companyprofile_last_post_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name=""),
        ),
    ]
