# Generated by Django 5.0.6 on 2024-08-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_employerrequest_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employerrequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
