# Generated by Django 5.0.6 on 2024-08-25 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_remove_companyprofile_user_companyprofile_bik_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_profiles",
                to="users.userprofile",
            ),
        ),
    ]
