# Generated by Django 5.0.6 on 2024-08-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_companyprofile_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="employerrequest",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
