# Generated by Django 5.0.6 on 2024-08-28 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_employerrequest_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companyprofile",
            name="user_profile",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_profile",
                to="users.userprofile",
            ),
        ),
    ]
