# Generated by Django 5.0.6 on 2024-09-12 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0034_resume"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Resume",
        ),
    ]
