# Generated by Django 5.0.6 on 2024-09-15 07:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0035_delete_resume"),
    ]

    operations = [
        migrations.AddField(
            model_name="companyprofile",
            name="about",
            field=models.TextField(blank=True, null=True),
        ),
    ]
