# Generated by Django 5.0.6 on 2024-06-28 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_deposit_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'verbose_name': 'Депозит', 'verbose_name_plural': 'Депозиты'},
        ),
    ]
