# Generated by Django 5.0.6 on 2024-06-25 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, choices=[('tse', 'Астана'), ('ala', 'Алматы'), ('sco', 'Актау'), ('krg', 'Караганда'), ('ust', 'Усть-Каменагорск'), ('shym', 'Шымкент')], default='tse', max_length=25),
        ),
    ]
