# Generated by Django 5.0.6 on 2024-06-26 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='time_count',
            field=models.CharField(blank=True, choices=[('full', 'Полная занятость'), ('part', 'Договорная занятость'), ('daily', 'Единоразовая услуга')], max_length=155),
        ),
    ]
