# Generated by Django 5.0.6 on 2024-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_category_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
