# Generated by Django 5.0.6 on 2024-08-22 11:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_category_icon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Service",
        ),
    ]
