# Generated by Django 5.0.6 on 2024-09-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_alter_job_keys_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="keys_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="skills_description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
