# Generated by Django 5.0.6 on 2024-09-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0012_alter_job_keys_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
