# Generated by Django 5.0.6 on 2024-09-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0014_jobresponse"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobresponse",
            name="message",
            field=models.TextField(blank=True, null=True),
        ),
    ]
