# Generated by Django 5.0.6 on 2024-09-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0015_alter_jobresponse_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobresponse",
            name="status",
            field=models.CharField(
                choices=[
                    ("accepted", "Принят"),
                    ("rejected", "Отклонен"),
                    ("pending", "На рассмотрении"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
